New-NetFirewallRule -DisplayName "CSI8v3 80 In" -Direction Inbound -LocalPort 80 -Protocol TCP -Action Allow  
New-NetFirewallRule -DisplayName "CSI8v3 80 Out" -Direction Outbound -LocalPort 80 -Protocol TCP -Action Allow 
New-NetFirewallRule -DisplayName "CSI8v3 443 In" -Direction Inbound -LocalPort 443 -Protocol TCP -Action Allow 
New-NetFirewallRule -DisplayName "CSI8v3 443 Out" -Direction Outbound -LocalPort 443 -Protocol TCP -Action Allow  
New-NetFirewallRule -DisplayName "CSI8v3 9002 In" -Direction Inbound -LocalPort 9002 -Protocol TCP -Action Allow  
New-NetFirewallRule -DisplayName "CSI8v3 9002 Out" -Direction Outbound -LocalPort 9002 -Protocol TCP -Action Allow 
New-NetFirewallRule -DisplayName "CSI8v3 9005 In" -Direction Inbound -LocalPort 9005 -Protocol TCP -Action Allow 
New-NetFirewallRule -DisplayName "CSI8v3 9005 Out" -Direction Outbound -LocalPort 9005 -Protocol TCP -Action Allow
New-NetFirewallRule -DisplayName "CSI8v3 9999 In" -Direction Inbound -LocalPort 9999 -Protocol TCP -Action Allow 
New-NetFirewallRule -DisplayName "CSI8v3 9999 Out" -Direction Outbound -LocalPort 9999 -Protocol TCP -Action Allow
New-NetFirewallRule -DisplayName "CSI8v3 10001-10100 In" -Direction Inbound -LocalPort 10001-10100 -Protocol TCP -Action Allow
New-NetFirewallRule -DisplayName "CSI8v3 10001-10100 Out" -Direction Outbound -LocalPort 10001-10100 -Protocol TCP -Action Allow 
New-NetFirewallRule -DisplayName "CSI8v3 50000 In" -Direction Inbound -LocalPort 50000 -Protocol TCP -Action Allow 
New-NetFirewallRule -DisplayName "CSI8v3 50000 Out" -Direction Outbound -LocalPort 50000 -Protocol TCP -Action Allow 
New-NetFirewallRule -DisplayName "CSI8v3 50920 In" -Direction Inbound -LocalPort 50920 -Protocol UDP -Action Allow 
New-NetFirewallRule -DisplayName "CSI8v3 50920 Out" -Direction Outbound -LocalPort 50920 -Protocol UDP -Action Allow 
New-NetFirewallRule -DisplayName "CSI8v3 52540 In" -Direction Inbound -LocalPort 52540 -Protocol TCP -Action Allow 
New-NetFirewallRule -DisplayName "CSI8v3 52540 Out" -Direction Outbound -LocalPort 52540 -Protocol TCP -Action Allow 
New-NetFirewallRule -DisplayName "CSI8v3 52541 In" -Direction Inbound -LocalPort 52541 -Protocol TCP -Action Allow 
New-NetFirewallRule -DisplayName "CSI8v3 52541 Out" -Direction Outbound -LocalPort 52541 -Protocol TCP -Action Allow 